sudo: required
services:
  - docker
before_install:
  - docker build -t leoenes/multi-docker-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true leoenes/multi-docker-test npm run test -- --coverage
after_success:
  - docker build -t $DOCKER_ID/multi-docker-client ./client
  - docker build -t $DOCKER_ID/multi-docker-nginx ./nginx
  - docker build -t $DOCKER_ID/multi-docker-server ./server
  - docker build -t $DOCKER_ID/multi-docker-worker ./worker
  #Log in to the Docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # Take those images and push them to docker hub
  - docker push $DOCKER_ID/multi-docker-client
  - docker push $DOCKER_ID/multi-docker-nginx
  - docker push $DOCKER_ID/multi-docker-server
  - docker push $DOCKER_ID/multi-docker-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "sa-east-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-sa-east-1-209358974659"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY